/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, copyDefault, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && (copyDefault || key !== "default"))
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toCommonJS = /* @__PURE__ */ ((cache) => {
  return (module2, temp) => {
    return cache && cache.get(module2) || (temp = __reExport(__markAsModule({}), module2, 1), cache && cache.set(module2, temp), temp);
  };
})(typeof WeakMap !== "undefined" ? /* @__PURE__ */ new WeakMap() : 0);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SingleHtmlExporterPlugin
});
var import_obsidian4 = require("obsidian");

// src/ui/settings.ts
var import_obsidian = require("obsidian");
var SingleHtmlSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Rendering delay (ms)").setDesc("The amount of time to wait for dynamic content (like Mermaid or MathJax) to render before capturing the HTML.").addText((text) => text.setPlaceholder("500").setValue(this.plugin.settings.renderDelay.toString()).onChange(async (value) => {
      const numValue = parseInt(value);
      if (!isNaN(numValue) && numValue >= 0) {
        this.plugin.settings.renderDelay = numValue;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Include note title").setDesc("Include the note title as an H1 at the top of the exported HTML.").addToggle((toggle) => toggle.setValue(this.plugin.settings.includeTitle).onChange(async (value) => {
      this.plugin.settings.includeTitle = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Open after export").setDesc("Automatically open the exported HTML file in your default browser.").addToggle((toggle) => toggle.setValue(this.plugin.settings.openAfterExport).onChange(async (value) => {
      this.plugin.settings.openAfterExport = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Enable image zoom (open in new tab)").setDesc("Clicking on an image in the exported HTML will open its original size in a new browser tab.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableImageZoom).onChange(async (value) => {
      this.plugin.settings.enableImageZoom = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/exporter/renderer.ts
var import_obsidian2 = require("obsidian");

// src/exporter/observer.ts
var RenderingObserver = class {
  async waitForRendering(container, timeoutMs) {
    await new Promise((resolve) => setTimeout(resolve, 50));
    return new Promise((resolve) => {
      const checkFinished = () => {
        const mermaidElements = container.querySelectorAll(".mermaid");
        const mermaidBlocks = container.querySelectorAll('pre[class*="language-mermaid"], code[class*="language-mermaid"], .block-language-mermaid');
        if (mermaidElements.length === 0 && mermaidBlocks.length === 0) {
        } else {
          for (const el of Array.from(mermaidElements)) {
            if (!el.hasAttribute("data-processed") || !el.querySelector("svg")) {
              return false;
            }
          }
          for (const el of Array.from(mermaidBlocks)) {
            if (!el.querySelector(".mermaid[data-processed] svg")) {
              if (el.classList.contains("mermaid") && el.hasAttribute("data-processed") && el.querySelector("svg")) {
                continue;
              }
              return false;
            }
          }
        }
        const mathJax = container.querySelectorAll(".MathJax");
        if (mathJax.length > 0) {
        }
        return true;
      };
      if (checkFinished()) {
        resolve();
        return;
      }
      const observer = new MutationObserver(() => {
        if (checkFinished()) {
          cleanup();
          resolve();
        }
      });
      observer.observe(container, {
        attributes: true,
        childList: true,
        subtree: true
      });
      const timeoutId = setTimeout(() => {
        cleanup();
        resolve();
      }, timeoutMs);
      const cleanup = () => {
        observer.disconnect();
        clearTimeout(timeoutId);
      };
    });
  }
};

// src/exporter/renderer.ts
var MarkdownHtmlRenderer = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
    this.observer = new RenderingObserver();
  }
  async render(markdown, sourcePath) {
    const container = document.createElement("div");
    container.classList.add("markdown-rendered");
    container.style.position = "absolute";
    container.style.left = "-9999px";
    container.style.top = "-9999px";
    container.style.visibility = "hidden";
    container.style.width = "1000px";
    document.body.appendChild(container);
    const component = new import_obsidian2.Component();
    component.load();
    try {
      await import_obsidian2.MarkdownRenderer.render(this.app, markdown, container, sourcePath, component);
      await this.observer.waitForRendering(container, this.settings.renderDelay);
      return container.innerHTML;
    } finally {
      component.unload();
      if (container.parentNode) {
        container.parentNode.removeChild(container);
      }
    }
  }
};

// src/exporter/styles.ts
var StyleManager = class {
  getActiveStyles() {
    const styles = [];
    for (let i = 0; i < document.styleSheets.length; i++) {
      const sheet = document.styleSheets[i];
      try {
        const href = sheet.href || "";
        const ownerNode = sheet.ownerNode;
        const id = ownerNode ? ownerNode.id || "" : "";
        if (href.includes("/plugins/") || id.startsWith("plugin-")) {
          continue;
        }
        const rules = sheet.cssRules;
        if (rules) {
          for (let j = 0; j < rules.length; j++) {
            styles.push(rules[j].cssText);
          }
        }
      } catch (e) {
        console.warn("Could not access stylesheet rules:", sheet.href, e);
      }
    }
    styles.push(this.collectCssVariables());
    return styles.join("\n");
  }
  getBodyClasses() {
    return document.body.className;
  }
  collectCssVariables() {
    const body = document.body;
    const computedStyle = window.getComputedStyle(body);
    const variables = [];
    variables.push("body {");
    for (let i = 0; i < computedStyle.length; i++) {
      const propertyName = computedStyle.item(i);
      if (propertyName.startsWith("--")) {
        const value = computedStyle.getPropertyValue(propertyName);
        if (value) {
          variables.push(`  ${propertyName}: ${value.trim()};`);
        }
      }
    }
    variables.push("}");
    return variables.join("\n");
  }
};

// src/exporter/resources.ts
var import_obsidian3 = require("obsidian");
var ResourceManager = class {
  constructor(app) {
    this.app = app;
  }
  async collectResources(html, sourcePath) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(html, "text/html");
    const resourceSelectors = [
      { tag: "img", attr: "src" },
      { tag: "audio", attr: "src" },
      { tag: "video", attr: "src" },
      { tag: "source", attr: "src" },
      { tag: "track", attr: "src" },
      { tag: "iframe", attr: "src" }
    ];
    const resources = [];
    const fileCache = /* @__PURE__ */ new Map();
    const processedLocations = /* @__PURE__ */ new Set();
    for (const { tag, attr } of resourceSelectors) {
      const elements = Array.from(doc.querySelectorAll(tag));
      for (const el of elements) {
        const originalSrc = el.getAttribute(attr);
        if (!originalSrc || processedLocations.has(originalSrc))
          continue;
        if (tag === "iframe" && this.isYoutubeUrl(originalSrc)) {
          processedLocations.add(originalSrc);
          try {
            const videoId = this.extractYoutubeVideoId(originalSrc);
            if (videoId) {
              const resourceData = await this.loadYoutubeThumbnail(videoId);
              if (resourceData) {
                resources.push({
                  ...resourceData,
                  location: originalSrc
                });
              }
            }
          } catch (error) {
            console.warn(`Failed to load YouTube thumbnail for: ${originalSrc}`, error);
          }
          continue;
        }
        if (originalSrc.startsWith("http://") || originalSrc.startsWith("https://")) {
          processedLocations.add(originalSrc);
          try {
            const resourceData = await this.loadExternalResourceData(originalSrc);
            if (resourceData) {
              resources.push({
                ...resourceData,
                location: originalSrc
              });
            }
          } catch (error) {
            console.warn(`Failed to load external resource: ${originalSrc}`, error);
          }
          continue;
        }
        const normalizedPath = this.normalizeResourcePath(originalSrc);
        if (!normalizedPath)
          continue;
        const file = this.app.metadataCache.getFirstLinkpathDest(normalizedPath, sourcePath);
        if (file instanceof import_obsidian3.TFile) {
          processedLocations.add(originalSrc);
          try {
            let resourceData = fileCache.get(file.path);
            if (!resourceData) {
              resourceData = await this.loadResourceData(file);
              fileCache.set(file.path, resourceData);
            }
            resources.push({
              ...resourceData,
              location: originalSrc
            });
          } catch (error) {
            console.warn(`Failed to load resource: ${originalSrc}`, error);
          }
        } else {
          if (!originalSrc.startsWith("http") && !originalSrc.startsWith("data:")) {
            console.debug(`Resource not found in vault: ${normalizedPath} (original: ${originalSrc})`);
          }
        }
      }
    }
    return resources;
  }
  async collectResourcesFromCss(css) {
    const resources = [];
    const urlRegex = /url\(['"]?([^'")]+)['"]?\)/gi;
    const processedUrls = /* @__PURE__ */ new Set();
    let match;
    while ((match = urlRegex.exec(css)) !== null) {
      const originalUrl = match[1];
      if (processedUrls.has(originalUrl) || originalUrl.startsWith("data:"))
        continue;
      processedUrls.add(originalUrl);
      if (originalUrl.startsWith("http://") || originalUrl.startsWith("https://")) {
        try {
          const resourceData = await this.loadExternalResourceData(originalUrl);
          if (resourceData) {
            resources.push({
              ...resourceData,
              location: originalUrl
            });
          }
        } catch (error) {
          console.warn(`Failed to load external CSS resource: ${originalUrl}`, error);
        }
        continue;
      }
      const normalizedPath = this.normalizeResourcePath(originalUrl);
      if (!normalizedPath)
        continue;
      const file = this.app.metadataCache.getFirstLinkpathDest(normalizedPath, "");
      if (file instanceof import_obsidian3.TFile) {
        try {
          const resourceData = await this.loadResourceData(file);
          resources.push({
            ...resourceData,
            location: originalUrl
          });
        } catch (error) {
          console.warn(`Failed to load local CSS resource: ${originalUrl}`, error);
        }
      }
    }
    return resources;
  }
  normalizeResourcePath(src) {
    if (src.startsWith("data:") || src.startsWith("http:") || src.startsWith("https:")) {
      return null;
    }
    let path = src;
    if (path.startsWith("app://")) {
      path = path.replace(/^app:\/\/[^\/]+\//, "");
    }
    path = path.split(/[?#]/)[0];
    try {
      path = decodeURIComponent(path);
    } catch (e) {
    }
    const adapter = this.app.vault.adapter;
    if (adapter && typeof adapter.getBasePath === "function") {
      const basePath = adapter.getBasePath().replace(/\\/g, "/");
      const lowerPath = path.toLowerCase();
      const lowerBasePath = basePath.toLowerCase();
      if (lowerPath.startsWith(lowerBasePath)) {
        path = path.substring(basePath.length);
        if (path.startsWith("/")) {
          path = path.substring(1);
        }
      }
    }
    return path;
  }
  async loadExternalResourceData(url) {
    try {
      const response = await (0, import_obsidian3.requestUrl)({ url, method: "GET" });
      if (response.status !== 200) {
        console.warn(`Failed to download external resource: ${url} (Status: ${response.status})`);
        return null;
      }
      const buffer = response.arrayBuffer;
      const base64Data = (0, import_obsidian3.arrayBufferToBase64)(buffer);
      let mimeType = response.headers["content-type"] || response.headers["Content-Type"];
      if (!mimeType) {
        const urlWithoutQuery2 = url.split(/[?#]/)[0];
        const extension = urlWithoutQuery2.split(".").pop() || "";
        mimeType = this.getMimeType(extension);
      } else {
        mimeType = mimeType.split(";")[0].trim();
      }
      const urlWithoutQuery = url.split(/[?#]/)[0];
      const fileName = urlWithoutQuery.split("/").pop() || "external_resource";
      const cid = this.generateCid(fileName);
      return { cid, data: base64Data, mime: mimeType };
    } catch (error) {
      console.warn(`Error downloading external resource: ${url}`, error);
      return null;
    }
  }
  async loadResourceData(file) {
    const buffer = await this.app.vault.readBinary(file);
    const base64Data = (0, import_obsidian3.arrayBufferToBase64)(buffer);
    const mimeType = this.getMimeType(file.extension);
    const cid = this.generateCid(file.name);
    return { cid, data: base64Data, mime: mimeType };
  }
  generateCid(fileName) {
    const randomPart = Math.random().toString(36).substring(2, 11);
    const timestamp = Date.now();
    const safeName = fileName.replace(/[^a-zA-Z0-9]/g, "_");
    return `${safeName}.${randomPart}.${timestamp}@obsidian.html`;
  }
  getMimeType(extension) {
    const mimeMap = {
      "png": "image/png",
      "jpg": "image/jpeg",
      "jpeg": "image/jpeg",
      "gif": "image/gif",
      "webp": "image/webp",
      "svg": "image/svg+xml",
      "bmp": "image/bmp",
      "ico": "image/x-icon",
      "pdf": "application/pdf",
      "mp4": "video/mp4",
      "webm": "video/webm",
      "ogv": "video/ogg",
      "mp3": "audio/mpeg",
      "wav": "audio/wav",
      "ogg": "audio/ogg",
      "woff": "font/woff",
      "woff2": "font/woff2",
      "ttf": "font/ttf",
      "otf": "font/otf",
      "eot": "application/vnd.ms-fontobject"
    };
    return mimeMap[extension.toLowerCase()] || "application/octet-stream";
  }
  isYoutubeUrl(url) {
    return url.includes("youtube.com") || url.includes("youtu.be") || url.includes("youtube-nocookie.com") || url.includes("saved_resource.html") || /[?&]v=[a-zA-Z0-9_-]{11}/.test(url);
  }
  extractYoutubeVideoId(url) {
    const standardRegex = /(?:youtube(?:-nocookie)?\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?|shorts)\/|.*[?&]v=)|youtu\.be\/)([^"&?\/\s]{11})/i;
    let match = url.match(standardRegex);
    if (match)
      return match[1];
    const vParamRegex = /[?&]v=([^"&?\/\s]{11})/i;
    match = url.match(vParamRegex);
    return match ? match[1] : null;
  }
  async loadYoutubeThumbnail(videoId) {
    const qualities = ["maxresdefault", "hqdefault", "mqdefault", "default"];
    for (const quality of qualities) {
      const url = `https://img.youtube.com/vi/${videoId}/${quality}.jpg`;
      try {
        const response = await (0, import_obsidian3.requestUrl)({ url, method: "GET" });
        if (response.status === 200) {
          const buffer = response.arrayBuffer;
          const base64Data = (0, import_obsidian3.arrayBufferToBase64)(buffer);
          const cid = this.generateCid(`youtube_${videoId}_${quality}.jpg`);
          return { cid, data: base64Data, mime: "image/jpeg" };
        }
      } catch (error) {
      }
    }
    return null;
  }
};

// src/exporter/packer.ts
var HtmlPacker = class {
  pack(html, css, resources, bodyClasses = "", title = "Obsidian Export", includeTitle = false, enableImageZoom = true) {
    let fullHtml = html;
    const titleHtml = includeTitle ? `<h1>${title}</h1>
` : "";
    const finalBodyClasses = bodyClasses.includes("print") ? bodyClasses : `${bodyClasses} print`.trim();
    if (!fullHtml.toLowerCase().includes("<html")) {
      fullHtml = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title}</title>
</head>
<body class="${finalBodyClasses}">
<div class="app-container">
<div class="markdown-reading-view">
<div class="markdown-preview-view markdown-rendered">
${titleHtml}${fullHtml}
</div>
</div>
</div>
</body>
</html>`;
    }
    let layoutOverrideCss = `
		/* Override Obsidian's default app layout for a flat document */
		html, body {
			overflow: auto !important;
			background-color: var(--background-primary, #ffffff) !important;
			color: var(--text-normal, #000000) !important;
			width: 100% !important;
			margin: 0 !important;
			padding: 0 !important;
		}
		.app-container, .markdown-reading-view, .markdown-preview-view {
			position: static !important;
			display: block !important;
			overflow: visible !important;
			width: 100% !important;
			height: auto !important;
			/* CRITICAL: Reset stacking context triggers to ensure position: fixed 
			   works relative to the viewport, not these containers. */
			transform: none !important;
			contain: none !important;
			perspective: none !important;
			filter: none !important;
			backdrop-filter: none !important;
		}
		.markdown-reading-view {
			max-width: 900px !important;
			margin: 0 auto !important;
			padding: 40px !important;
		}
		.markdown-rendered {
			opacity: 1 !important;
			visibility: visible !important;
			height: auto !important;
			contain: none !important; /* Fix for blank screens */
		}
		.markdown-rendered img {
			max-width: 100% !important;
			height: auto !important;
		}
		.markdown-rendered .image-link {
			cursor: zoom-in;
			display: inline-block;
			max-width: 100%;
		}

		/* YouTube Thumbnail Link Styles */
		.youtube-embed-wrapper {
			max-width: 600px;
			margin: 1.5em auto;
		}
		.youtube-embed-replacement {
			position: relative;
			display: block;
			width: 100%;
			aspect-ratio: 16 / 9;
			background-color: #000;
			cursor: pointer;
			text-decoration: none !important;
			border-radius: 8px;
			overflow: hidden;
			box-shadow: 0 4px 15px rgba(0,0,0,0.1);
		}
		.youtube-embed-replacement img {
			width: 100%;
			height: 100%;
			object-fit: cover;
			opacity: 0.9;
			transition: opacity 0.2s, transform 0.3s;
		}
		.youtube-embed-replacement:hover img {
			opacity: 1;
			transform: scale(1.02);
		}
		.youtube-play-button {
			position: absolute;
			top: 50%;
			left: 50%;
			transform: translate(-50%, -50%);
			width: 68px;
			height: 48px;
			background: rgba(255, 0, 0, 0.9);
			border-radius: 12px;
			display: flex;
			align-items: center;
			justify-content: center;
			transition: background 0.2s, transform 0.2s;
			z-index: 2;
		}
		.youtube-embed-replacement:hover .youtube-play-button {
			background: rgba(255, 0, 0, 1);
			transform: translate(-50%, -50%) scale(1.1);
		}
		.youtube-play-button div {
			width: 0;
			height: 0;
			border-style: solid;
			border-width: 10px 0 10px 20px;
			border-color: transparent transparent transparent white;
			margin-left: 4px;
		}

		/* Print Styles - Basic overrides (Nuclear Reset v2 will handle the heavy lifting) */
		@media print {
			.youtube-play-button {
				display: none !important; /* Hide play button on print */
			}
		}
		`;
    if (enableImageZoom) {
      fullHtml = this.wrapImagesInLinks(fullHtml);
    }
    let consolidatedCss = css + "\n" + layoutOverrideCss;
    consolidatedCss = this.replaceResourceLinksInCss(consolidatedCss, resources);
    let processedHtml = this.injectStyles(fullHtml, consolidatedCss);
    processedHtml = this.injectNuclearPrintReset(processedHtml);
    processedHtml = this.unescapeImageSrc(processedHtml);
    processedHtml = this.replaceResourceLinks(processedHtml, resources);
    processedHtml = this.replaceYoutubeIframes(processedHtml, resources);
    if (enableImageZoom) {
      processedHtml = this.injectDataUriBypassScript(processedHtml);
    }
    return processedHtml;
  }
  injectDataUriBypassScript(html) {
    const script = `
		<script id="data-uri-bypass">
		document.addEventListener('click', function(e) {
			const link = e.target.closest('a.image-link');
			if (link && link.href && link.href.startsWith('data:image/')) {
				e.preventDefault();
				const dataUri = link.getAttribute('href');
				const win = window.open();
				if (win) {
					win.document.write('<html><head><title>Image Preview</title><style>body { margin: 0; display: flex; align-items: center; justify-content: center; background: #202020; min-height: 100vh; } img { max-width: 100%; height: auto; cursor: zoom-out; }</style></head><body onclick="window.close()"><img src="' + dataUri + '"></body></html>');
					win.document.close();
				} else {
					console.error('Failed to open image preview window. Pop-up blocker might be active.');
				}
			}
		}, true);
		<\/script>`;
    if (html.includes("</body>")) {
      return html.replace("</body>", `${script}
</body>`);
    } else {
      return html + script;
    }
  }
  injectNuclearPrintReset(html) {
    const resetCss = `
		<style id="nuclear-print-reset">
		@media print {
			/* Nuclear Reset v2: Use highest possible specificity by targeting body explicitly */
			html, body {
				display: block !important;
				overflow: visible !important;
				height: auto !important;
				min-height: 100% !important;
				background: white !important;
				color: black !important;
				contain: none !important;
				margin: 0 !important;
				padding: 0 !important;
				print-color-adjust: exact;
				-webkit-print-color-adjust: exact;
			}

			/* Force display of the entire hierarchy from body down to the content.
			   We target body.print to ensure we win against Obsidian's internal !important rules. */
			body.print,
			body.print .app-container, 
			body.print .markdown-reading-view, 
			body.print .markdown-preview-view, 
			body.print .markdown-rendered {
				display: block !important;
				visibility: visible !important;
				opacity: 1 !important;
				position: static !important;
				height: auto !important;
				min-height: 100% !important;
				width: 100% !important;
				overflow: visible !important;
				contain: none !important;
			}

			/* Target the specific container that is often hidden by Obsidian's print style */
			body.print > .app-container {
				display: block !important;
			}

			/* Ensure background colors and images are printed for all elements */
			* {
				print-color-adjust: exact !important;
				-webkit-print-color-adjust: exact !important;
			}

			/* Re-hide only the things we definitely don't want */
			.titlebar, .status-bar, .sidebar, .ribbon, .nav-header, .view-header {
				display: none !important;
			}
			.youtube-play-button {
				display: none !important; /* Hide play button on print */
			}
		}
		</style>`;
    if (html.includes("</body>")) {
      return html.replace("</body>", `${resetCss}
</body>`);
    } else {
      return html + resetCss;
    }
  }
  injectStyles(html, css) {
    const styleTag = `<style>
${css}
</style>`;
    if (html.includes("</head>")) {
      return html.replace("</head>", `${styleTag}
</head>`);
    } else if (html.includes("<body>")) {
      return html.replace("<body>", `<head>
${styleTag}
</head>
<body>`);
    } else {
      return `${styleTag}
${html}`;
    }
  }
  replaceResourceLinks(html, resources) {
    let result = html;
    for (const resource of resources) {
      if (resource.location.includes("youtube.com") || resource.location.includes("youtu.be") || resource.location.includes("youtube-nocookie.com") || resource.location.includes("saved_resource.html") || /[?&]v=[a-zA-Z0-9_-]{11}/.test(resource.location)) {
        continue;
      }
      const dataUri = `data:${resource.mime};base64,${resource.data}`;
      const escapedLocation = resource.location.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const regex = new RegExp(`((?:src|href)=["'])${escapedLocation}(["'])`, "g");
      result = result.replace(regex, `$1${dataUri}$2`);
    }
    return result;
  }
  replaceResourceLinksInCss(css, resources) {
    let result = css;
    for (const resource of resources) {
      const dataUri = `data:${resource.mime};base64,${resource.data}`;
      const escapedLocation = resource.location.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const regex = new RegExp(`url\\(['"]?${escapedLocation}['"]?\\)`, "g");
      result = result.replace(regex, `url("${dataUri}")`);
    }
    return result;
  }
  replaceYoutubeIframes(html, resources) {
    let result = html;
    const youtubeResources = resources.filter((r) => r.location.includes("youtube.com") || r.location.includes("youtu.be") || r.location.includes("youtube-nocookie.com") || r.location.includes("saved_resource.html") || /[?&]v=[a-zA-Z0-9_-]{11}/.test(r.location));
    if (youtubeResources.length === 0)
      return result;
    const youtubeMap = /* @__PURE__ */ new Map();
    for (const res of youtubeResources) {
      youtubeMap.set(res.location, res);
    }
    const anyIframeRegex = /<iframe[\s\S]*?src=["']([^"']+)["'][\s\S]*?>[\s\S]*?<\/iframe>/gi;
    result = result.replace(anyIframeRegex, (match, src) => {
      const unescapedSrc = src.replace(/&amp;/g, "&");
      const resource = youtubeMap.get(src) || youtubeMap.get(unescapedSrc);
      if (resource) {
        const dataUri = `data:${resource.mime};base64,${resource.data}`;
        const videoUrl = resource.location;
        const videoId = this.extractYoutubeVideoId(videoUrl);
        const watchUrl = videoId ? `https://www.youtube.com/watch?v=${videoId}` : videoUrl;
        return `<div class="youtube-embed-wrapper"><a href="${watchUrl}" target="_blank" class="youtube-embed-replacement"><img src="${dataUri}" alt="YouTube Video"><div class="youtube-play-button"><div></div></div></a></div>`;
      }
      return match;
    });
    return result;
  }
  extractYoutubeVideoId(url) {
    const standardRegex = /(?:youtube(?:-nocookie)?\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?|shorts)\/|.*[?&]v=)|youtu\.be\/)([^"&?\/\s]{11})/i;
    let match = url.match(standardRegex);
    if (match)
      return match[1];
    const vParamRegex = /[?&]v=([^"&?\/\s]{11})/i;
    match = url.match(vParamRegex);
    return match ? match[1] : null;
  }
  wrapImagesInLinks(html) {
    const anchors = [];
    let tempHtml = html.replace(/<a[\s\S]*?<\/a>/gi, (match) => {
      anchors.push(match);
      return `___HTML_ANCHOR_${anchors.length - 1}___`;
    });
    tempHtml = tempHtml.replace(/<img([^>]+)>/gi, (match, attrs) => {
      if (attrs.includes("youtube-embed-replacement"))
        return match;
      const srcMatch = attrs.match(/src=["'](.*?)["']/i);
      const src = srcMatch ? srcMatch[1] : "";
      return `<a href="${src}" target="_blank" class="image-link"><img${attrs}></a>`;
    });
    return tempHtml.replace(/___HTML_ANCHOR_(\d+)___/g, (match, index) => {
      return anchors[parseInt(index)];
    });
  }
  unescapeImageSrc(html) {
    return html.replace(/src=(["'])(.*?)\1/g, (match, quote, srcValue) => {
      const unescapedSrc = srcValue.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">");
      return `src=${quote}${unescapedSrc}${quote}`;
    });
  }
};

// src/exporter/controller.ts
var ExportController = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
    this.renderer = new MarkdownHtmlRenderer(app, settings);
    this.styleManager = new StyleManager();
    this.resourceManager = new ResourceManager(app);
    this.packer = new HtmlPacker();
  }
  async runExport(file) {
    try {
      const markdown = await this.app.vault.read(file);
      const html = await this.renderer.render(markdown, file.path);
      const css = this.styleManager.getActiveStyles();
      const bodyClasses = this.styleManager.getBodyClasses();
      const htmlResources = await this.resourceManager.collectResources(html, file.path);
      const cssResources = await this.resourceManager.collectResourcesFromCss(css);
      const allResources = [...htmlResources, ...cssResources];
      const finalHtml = this.packer.pack(html, css, allResources, bodyClasses, file.basename, this.settings.includeTitle, this.settings.enableImageZoom);
      return finalHtml;
    } catch (error) {
      console.error("Single HTML Export failed:", error);
      throw new Error(`Failed to export "${file.name}" to Single HTML: ${error instanceof Error ? error.message : String(error)}`);
    }
  }
};

// src/utils/file-system.ts
async function showSaveDialog(defaultName) {
  try {
    const electron = require("electron");
    const remote = electron.remote;
    const dialog = remote ? remote.dialog : electron.dialog;
    if (!dialog) {
      throw new Error("Electron dialog API not available.");
    }
    const result = await dialog.showSaveDialog({
      title: "Export to Single HTML",
      defaultPath: defaultName,
      filters: [
        { name: "HTML Files", extensions: ["html"] },
        { name: "All Files", extensions: ["*"] }
      ]
    });
    if (result.canceled || !result.filePath) {
      return null;
    }
    return result.filePath;
  } catch (error) {
    console.error("Failed to show save dialog:", error);
    throw error;
  }
}
async function writeToFile(filePath, data) {
  try {
    const fs = require("fs");
    return new Promise((resolve, reject) => {
      fs.writeFile(filePath, data, "utf8", (err) => {
        if (err) {
          reject(err);
        } else {
          resolve();
        }
      });
    });
  } catch (error) {
    console.error("Failed to write file:", error);
    throw error;
  }
}

// src/main.ts
var DEFAULT_SETTINGS = {
  renderDelay: 500,
  includeTitle: false,
  openAfterExport: false,
  enableImageZoom: true
};
var SingleHtmlExporterPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.controller = new ExportController(this.app, this.settings);
    this.addSettingTab(new SingleHtmlSettingTab(this.app, this));
    this.addCommand({
      id: "export-to-single-html",
      name: "Export to Single HTML",
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        const isMarkdown = (activeFile == null ? void 0 : activeFile.extension) === "md";
        if (import_obsidian4.Platform.isDesktop && activeFile && isMarkdown) {
          if (!checking) {
            this.exportFile(activeFile);
          }
          return true;
        }
        return false;
      }
    });
    console.log("Obsidian Single HTML Exporter loaded");
  }
  onunload() {
    console.log("Obsidian Single HTML Exporter unloaded");
  }
  async exportFile(file) {
    try {
      new import_obsidian4.Notice(`Exporting "${file.name}" to Single HTML...`);
      const html = await this.controller.runExport(file);
      const defaultName = `${file.basename}.html`;
      const filePath = await showSaveDialog(defaultName);
      if (!filePath) {
        new import_obsidian4.Notice("Export canceled.");
        return;
      }
      await writeToFile(filePath, html);
      new import_obsidian4.Notice(`Successfully exported to: ${filePath}`);
      if (this.settings.openAfterExport && import_obsidian4.Platform.isDesktop) {
        try {
          const { shell } = require("electron");
          await shell.openPath(filePath);
        } catch (e) {
          console.error("Failed to open file:", e);
        }
      }
    } catch (error) {
      console.error("Single HTML Export failed:", error);
      new import_obsidian4.Notice(`Export failed: ${error instanceof Error ? error.message : String(error)}`);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
module.exports = __toCommonJS(main_exports);
